# Generated by Django 4.2 on 2025-04-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='ссылка')),
                ('short_token', models.CharField(max_length=6, unique=True, verbose_name='токен короткой ссылки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='количество переходов')),
            ],
        ),
    ]
